baseURL: "https://www.hulin.dev"
defaultContentLanguage: "en"
languages:
  zh:
    contentDir: "content/zh"
    title: "INNER PEACE"
    menu:
      main:
        - name: 关于
          url: /zh/about
        - name: 技术
          url: /zh/tech
        - name: 工具
          url: /zh/tool
        - name: Archive
          url: /zh/categories
        - name: EN
          url: /en
  en:
    contentDir: "content/en"
    title: "INNER PEACE"
    menu:
      main:
        - name: About
          url: /about
        - name: 中文
          url: /zh

theme: "paper"
algolia:
  index: "blog"
  key: "093601b4bd8cea8a8c59a9f58ed2dad4"
  appID: "DIISOO4383"

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    style: gruvbox

params:
  avatar: "https://hulin.dev/images/loog.png"
  github: "https://github.com/hulin32"
  linkedin: "https://www.linkedin.com/in/lin-hu-247638117"
  giscus:
    repo: "hulin32/blog"
    repoId: "MDEwOlJlcG9zaXRvcnkxMDkxMDEyODI"
    category: "Announcements"
    categoryId: "DIC_kwDOBoDA4s4ChWGe"
    mapping: "url"
    strict: "1"
    reactionsEnabled: "1"
    emitMetadata: "1"
    inputPosition: "top"
    theme: "light_tritanopia"
    lang: "en"
    loading: "lazy"
